### ISSUE TITLE
Initial GitHub Setup

### ISSUE THREAD

**Issue by JLaveta** [ad440-cloud-project/DevOps#2]
Estimated task time: 3 hours

1, Setup and initialize GitHub Organization and Repository.
2. Create development branch, protect branches, set development as default.
3. Setup GitHub project board/tracker
4. Integrate ZenHub to access additional tools

**Comment by JLaveta** [comment]
GitHub -> TravisCI line is working fine, so this is good to close.

Total time: 2.5 hours.

**Comment by JLaveta** [comment]
GitHub repo setup complete. TravisCI implemented. No further action necessary here.

**Comment by gshields5541** [comment]
I’m working on the JavaScript file that represents the upload service. But I’m running into problems. Work time : 3 hours

**Comment by JLaveta** [comment]
@gshields5541 Does this have anything to do with GitHub setup?

If it does, please explain and reopen this issue. If not, please open a new issue and describe the issue.

**Comment by gshields5541** [comment]
The JavaScript file does the connection, in this case to the blob service. But I’ve been having problems with the code. I was hoping to meet with Tody to iron out how to setup it up, but I didn’t know you were meeting with him on campus and I left around 4:30

Gerald
